#!/bin/bash

set -e

bazel_version="0.21.0"
nccl_version="1.3.4-1"

# Validate environment
if ! which cmake; then
  sudo apt-get -y install cmake
fi

if ! which curl; then
  sudo apt-get -y install curl
fi

if ! which javac; then
  sudo apt-get -y install openjdk-8-jdk-headless
fi

#if ! which javac; then
#  sudo apt-get -y install openjdk-11-jdk-headless
#fi

# Install bazel
if ! which bazel; then
  if [[ ! -d "bazel-${bazel_version}-dist" ]]; then
    wget "https://github.com/bazelbuild/bazel/releases/download/${bazel_version}/bazel-${bazel_version}-dist.zip"
    unzip "bazel-${bazel_version}-dist.zip" -d bazel-${bazel_version}-dist
  fi

  cd "bazel-${bazel_version}-dist"

  if [[ ! -f "output/bazel" ]]; then
    env EXTRA_BAZEL_ARGS="--host_javabase=@local_jdk//:jdk" bash ./compile.sh
    sudo cp output/bazel /usr/local/bin/
  fi

  cd ..
fi

# Install NCCL
if [[ ! -d nccl ]]; then
  git clone https://github.com/NVIDIA/nccl.git
fi

cd "nccl"
git fetch --all
git checkout 6d8b242
make
make install
cd .. # nccl

# Install tensorflow_cc
cd tensorflow_cc/tensorflow_cc

if [[ ! -d build ]]; then
  mkdir build
fi

cd build
cmake -DTENSORFLOW_STATIC=OFF -DTENSORFLOW_SHARED=ON ..
nice make
cd .. # build
cd .. # tensorflow_cc
